# Generated by Django 6.0.3 on 2026-03-15 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedDomain',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('seed', 'Seed Data'), ('admin', 'Admin Added'), ('report', 'From Report')], default='manual', max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blacklist',
                'indexes': [models.Index(fields=['domain'], name='idx_blacklist_domain'), models.Index(fields=['source'], name='idx_blacklist_source'), models.Index(fields=['date_added'], name='idx_blacklist_date')],
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('safe', 'Safe'), ('suspicious', 'Suspicious'), ('phishing', 'Phishing')], db_index=True, default='pending', max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'urls',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url_length', models.IntegerField(default=0)),
                ('domain_length', models.IntegerField(default=0)),
                ('path_length', models.IntegerField(default=0)),
                ('num_dots', models.IntegerField(default=0)),
                ('num_hyphens', models.IntegerField(default=0)),
                ('num_subdomains', models.IntegerField(default=0)),
                ('num_query_params', models.IntegerField(default=0)),
                ('has_at_symbol', models.BooleanField(default=False)),
                ('has_ip_address', models.BooleanField(default=False)),
                ('uses_https', models.BooleanField(default=True)),
                ('has_double_slash_redirect', models.BooleanField(default=False)),
                ('has_suspicious_tld', models.BooleanField(default=False)),
                ('is_shortened', models.BooleanField(default=False)),
                ('has_suspicious_keywords', models.BooleanField(default=False)),
                ('num_suspicious_keywords', models.IntegerField(default=0)),
                ('has_hex_encoding', models.BooleanField(default=False)),
                ('has_punycode', models.BooleanField(default=False)),
                ('verdict', models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('phishing', 'Phishing')], db_index=True, max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('risk_score', models.IntegerField(default=0)),
                ('reasons', models.JSONField(default=list)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_result', to='scanner.url')),
            ],
            options={
                'db_table': 'scan_results',
            },
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['status'], name='idx_urls_status'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['date_submitted'], name='idx_urls_submitted'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['submitted_by'], name='idx_urls_user'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['status', 'date_submitted'], name='idx_urls_status_date'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['verdict'], name='idx_scan_verdict'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['confidence_score'], name='idx_scan_confidence'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['scanned_at'], name='idx_scan_date'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['risk_score'], name='idx_scan_score'),
        ),
    ]
