# Generated by Django 4.2.10 on 2026-08-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_url_lifecycle_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='domain_age_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='final_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='geo_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_external_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_password_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='http_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='page_title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='redirect_chain',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='risk_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='ssl_issuer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='ssl_valid_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='threat_intel_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='url',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('safe', 'Safe'), ('suspicious', 'Suspicious'), ('phishing', 'Phishing')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['verdict', 'scanned_at'], name='idx_scan_verdict_date'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['risk_score', 'verdict'], name='idx_scan_score_verdict'),
        ),
    ]
