# core/middleware.py
"""
WSGI / Django HTTP Error Monitoring Middleware for PhishGuard.
Captures unhandled 500/502/503 HTTP errors and unhandled exceptions at the middleware level.
"""
import logging
from accounts.error_monitoring import capture_exception

logger = logging.getLogger("core.middleware")


class ErrorMonitoringMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        try:
            response = self.get_response(request)
        except Exception as exc:
            capture_exception(exc, request=request, severity="critical", status_code=500)
            raise exc

        # Also capture 5xx server responses generated by non-DRF Django views
        if response.status_code >= 500:
            capture_exception(
                Exception(f"HTTP {response.status_code} Server Error"),
                request=request,
                severity="error",
                status_code=response.status_code,
                extra={"status_code": response.status_code},
            )

        return response
