# Generated by Django 6.0.3 on 2026-03-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='idx_users_joined',
        ),
    ]
