# Generated by Copilot on 2026-04-10
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_idx_users_joined"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("login_success", "Login Success"), ("login_failed", "Login Failed"), ("login_locked", "Login Locked"), ("register_success", "Register Success"), ("register_failed", "Register Failed")], db_index=True, max_length=32)),
                ("email", models.EmailField(blank=True, default="", max_length=150)),
                ("username", models.CharField(blank=True, default="", max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="security_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "security_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["event_type"], name="idx_sec_evt_type"),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["created_at"], name="idx_sec_evt_date"),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["ip_address"], name="idx_sec_evt_ip"),
        ),
    ]
