# Generated by Django 4.2.10 on 2026-08-08 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_securityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('scan', 'Threat Scanning'), ('blacklist', 'Blacklist Management'), ('report', 'Reports & Flagging'), ('account', 'Account Management'), ('system', 'System Events')], db_index=True, default='system', max_length=32)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical Security Alert')], db_index=True, default='info', max_length=16)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('blocked', 'Blocked / Throttle')], db_index=True, default='success', max_length=20)),
                ('user_email', models.EmailField(blank=True, default='', max_length=150)),
                ('user_role', models.CharField(blank=True, default='', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('request_path', models.CharField(blank=True, default='', max_length=255)),
                ('request_method', models.CharField(blank=True, default='', max_length=10)),
                ('target_resource', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='idx_audit_cat_date'), models.Index(fields=['event_type', 'created_at'], name='idx_audit_evt_date'), models.Index(fields=['severity', 'created_at'], name='idx_audit_sev_date'), models.Index(fields=['user', 'created_at'], name='idx_audit_usr_date'), models.Index(fields=['ip_address', 'created_at'], name='idx_audit_ip_date')],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key_prefix', models.CharField(db_index=True, max_length=12)),
                ('key_hash', models.CharField(db_index=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_prefix'], name='idx_apk_prefix'), models.Index(fields=['key_hash'], name='idx_apk_hash')],
            },
        ),
    ]
