# Generated by Django 4.2.10 on 2026-08-08 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_securityevent_id_auditlog_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exception_class', models.CharField(db_index=True, max_length=150)),
                ('message', models.TextField()),
                ('traceback', models.TextField()),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='error', max_length=20)),
                ('status_code', models.IntegerField(db_index=True, default=500)),
                ('request_path', models.CharField(db_index=True, max_length=255)),
                ('request_method', models.CharField(default='GET', max_length=10)),
                ('user_email', models.CharField(blank=True, default='', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_error_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'error_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', 'created_at'], name='idx_err_sev_date'), models.Index(fields=['exception_class', 'created_at'], name='idx_err_cls_date'), models.Index(fields=['is_resolved', 'created_at'], name='idx_err_res_date'), models.Index(fields=['status_code', 'created_at'], name='idx_err_st_date')],
            },
        ),
    ]
