# Generated by Django 4.2.10 on 2026-08-09 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, default='', max_length=150)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('path', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('method', models.CharField(blank=True, default='GET', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_ms', models.IntegerField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('browser', models.CharField(blank=True, default='', max_length=100)),
                ('os', models.CharField(blank=True, default='', max_length=100)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot / Crawler'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', max_length=5)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('isp', models.CharField(blank=True, default='', max_length=200)),
                ('referer', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'site_visits',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='idx_sv_ip_time'), models.Index(fields=['user', 'timestamp'], name='idx_sv_user_time'), models.Index(fields=['path', 'timestamp'], name='idx_sv_path_time'), models.Index(fields=['device_type'], name='idx_sv_device'), models.Index(fields=['country_code'], name='idx_sv_country')],
            },
        ),
    ]
